In [2]:
import json
import numpy as np
import os
from sentence_transformers import CrossEncoder
from FlagEmbedding import BGEM3FlagModel
from scipy.sparse import csr_matrix
import torch
from tqdm.notebook import tqdm
import pandas as pd
import ast
import google.generativeai as genai
import time
from PIL import Image
import re

In [ ]:
output_dir = '../cache/BGE+GTE/test'
if not os.path.exists(output_dir):
    os.makedirs(output_dir)

with open('../index.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

doc_ids = []
documents = []
doc_id_map = {}
doc_map = {} 

for idx, item in enumerate(data):
    doc_id = str(item['id'])
    text_content = item['text']
    doc_ids.append(doc_id)
    documents.append(text_content)
    doc_id_map[idx] = doc_id
    doc_map[doc_id] = (text_content, item['image_path'])

test_df = pd.read_csv('../data/test_Q.csv')
ids = test_df['id'].to_list()
questions = test_df['question'].to_list()

In [4]:
def lexical_to_csr(lexical_weights, vocab_size=250002):
    rows, cols, data_vals = [], [], []
    for row_idx, weight_dict in enumerate(lexical_weights):
        for token_id, score in weight_dict.items():
            rows.append(row_idx)
            cols.append(int(token_id))
            data_vals.append(float(score))
    return csr_matrix((data_vals, (rows, cols)), shape=(len(lexical_weights), vocab_size), dtype=np.float32)

retriever = BGEM3FlagModel('BAAI/bge-m3', use_fp16=True)

doc_output = retriever.encode(documents, batch_size=4, max_length=8192, return_dense=True, return_sparse=True, return_colbert_vecs=False)
doc_dense = doc_output['dense_vecs']
doc_sparse = lexical_to_csr(doc_output['lexical_weights'])

q_output = retriever.encode(questions, batch_size=4, max_length=512, return_dense=True, return_sparse=True, return_colbert_vecs=False)
q_dense = q_output['dense_vecs']
q_sparse = lexical_to_csr(q_output['lexical_weights'])

scores_dense = q_dense @ doc_dense.T
scores_sparse = (q_sparse @ doc_sparse.T).toarray()
scores_hybrid = scores_dense + (scores_sparse * 0.8)

top_k = 50
initial_hits = []

for i in tqdm(range(len(questions))):
    scores = scores_hybrid[i]
    top_n_indices = np.argsort(scores)[::-1][:top_k]
    
    hits = []
    for idx in top_n_indices:
        hits.append({
            'corpus_id': idx,
            'score': float(scores[idx])
        })
    initial_hits.append(hits)

del retriever, doc_output, q_output, scores_dense, scores_sparse, scores_hybrid
torch.cuda.empty_cache()

Fetching 30 files:   0%|          | 0/30 [00:00<?, ?it/s]

pre tokenize: 100%|██████████| 160/160 [00:00<00:00, 202.41it/s]
You're using a XLMRobertaTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
Inference Embeddings: 100%|██████████| 160/160 [00:27<00:00,  5.72it/s]
pre tokenize: 100%|██████████| 71/71 [00:00<00:00, 1328.16it/s]
Inference Embeddings: 100%|██████████| 71/71 [00:01<00:00, 62.98it/s]

  0%|          | 0/282 [00:00<?, ?it/s]

In [5]:
reranked_hits = []
final_top_k = 5
reranker = CrossEncoder("Alibaba-NLP/gte-multilingual-reranker-base", trust_remote_code=True, device='cuda')

print("Reranking...")
for i, hit in enumerate(tqdm(initial_hits)):
    query = questions[i]
    candidate_pairs = [[query, documents[result['corpus_id']]] for result in hit]
    scores = reranker.predict(candidate_pairs, batch_size=8, show_progress_bar=False)
    
    for j, result in enumerate(hit):
        result['score'] = scores[j]
        
    sorted_hit = sorted(hit, key=lambda x: x['score'], reverse=True)
    reranked_hits.append(sorted_hit[:final_top_k])

del reranker
torch.cuda.empty_cache()

Reranking...

  0%|          | 0/282 [00:00<?, ?it/s]

In [6]:
results_cache = {}

for i, hit in enumerate(reranked_hits):
    retrieved_ids = [doc_id_map[result['corpus_id']] for result in hit]
    results_cache[ids[i]] = retrieved_ids

with open(os.path.join(output_dir, 'results_cache.json'), 'w', encoding='utf-8') as f:
    json.dump(results_cache, f, indent=4)

In [7]:
with open(os.path.join(output_dir, 'results_cache.json'), 'r') as f:
    results_cache = json.load(f)

In [18]:
apikeys = ["AIzaSyA6ysKqVF8U_doCmTr2ja8bS7TdzZ0uBYM",
            "AIzaSyDQeGUVxQmd5HlLsvUZM1290K1X0TW8A3Y",
            "AIzaSyD0MPdCLbNaJL9Dfmm6EckKaHSwpoOx0lc",
            "AIzaSyBvDoEZGpFAuXuAiJTk8WC2HqSZf1PDdpY",
            "AIzaSyB97eTf8yamhDhO03bk64pVLeG5Pxp7WAk",
            "AIzaSyAza6g0ldah0cd2OFHenxMeWtp8PVxZD60"
            ]

df_partial = pd.read_csv('../data/submission_partial.csv') 
# df_partial = pd.DataFrame()
if not df_partial.empty:
    generated_results = df_partial.to_dict('records')
    processed_ids = set(df_partial['id'].astype(str))
else:
    generated_results = []
    processed_ids = set()

api_id = 0

for index, row in tqdm(test_df.iterrows(), total=len(test_df)):
    if str(row['id']) in processed_ids:
        continue
        
    q_id = row['id']
    question = row['question']
    unit = row['answer_unit']
    
    retrieved_doc_ids = results_cache.get(q_id, [])
    
    context_texts = []
    for rid in retrieved_doc_ids:
        context_texts.append(f"Document ID [{rid}]: {doc_map[rid]}")
    
    context_str = "\n\n".join(context_texts)
    
    prompt = f"""
    You are an expert in AI energy consumption and sustainability.
    Answer the question based ONLY on the provided Reference Documents, along with the unit to the question.
    You will be provided some texts, each is labeled as Document ID ##, and unit of the answer to the question.
    
    Format your output as a JSON object with the following keys:
    - answer: The natural language answer.
    - answer_value: The normalized numeric or categorical value (e.g., 1438, Water consumption, [5,10](for an interval answer, without space), 1/0(For true or False questions)). If not found, use "is_blank". 
    - ref_id: A list of document IDs that support the answer (e.g., ["doc_1", "doc_2"]). If no relative documents, return 'is_blank'
    - explanation: A short reasoning.

    Question: {question}, Unit: {unit}

    Reference Documents:
    {context_str}
    """ 
    
    retrieved_doc_ids = results_cache.get(str(q_id), [])
    
    cnt = 0
    while(True):
        cnt += 1
        try:
            genai.configure(api_key=apikeys[api_id%len(apikeys)])
            api_id += 1
            generation_config = {
                "temperature": 0.1,
                "top_p": 0.95,
                "top_k": 64,
                "max_output_tokens": 8192,
                "response_mime_type": "application/json",
            }
            model = genai.GenerativeModel(
                model_name="gemini-2.5-pro",
                generation_config=generation_config,
            )
            response = model.generate_content(prompt)
            res_json = json.loads(response.text)
            
            pred_ref_id = list(set([e.split('_')[0] for e in res_json.get('ref_id', [])]))
            pred_ref_id = ["is_blank"] if pred_ref_id == [] else pred_ref_id

            if isinstance(pred_ref_id, str):
                pred_ref_id = [pred_ref_id]
                
            generated_results.append({
                'id': q_id,
                'question': question,
                'answer': res_json.get('answer', 'is_blank'),
                'answer_value': res_json.get('answer_value', 'is_blank'),
                'answer_unit': unit,
                'ref_id': pred_ref_id,
                'ref_url': "is_blank",
                'supporting_materials': "is_blank",
                'explanation': res_json.get('explanation', 'is_blank'),
            })
            print(generated_results[-1])
            break
            
        except Exception as e:
            print(f"Error on {q_id}: {e}")
            if cnt > 3:
                generated_results.append({
                    'id': q_id,
                    'question': question,
                    'answer': "is_blank",
                    'answer_value': "is_blank",
                    'answer_unit': unit,
                    'ref_id': ["is_blank"],
                    'ref_url': "is_blank",
                    'supporting_materials': "is_blank",
                    'explanation': "is_blank",
                })
                break
            time.sleep(10)

    if index % 10 == 0:
        pd.DataFrame(generated_results).to_csv('../data/submission_partial.csv', index=False)

results_df = pd.DataFrame(generated_results)
results_df.to_csv('../data/submission.csv', index=0)

  0%|          | 0/282 [00:00<?, ?it/s]

{'id': 'q024', 'question': 'According to a cost estimation, how many zettaFLOPs were required to train the English portion of the FLM-101B model?', 'answer': 'According to the provided documents, the estimated cost to train the English portion of the FLM-101B model was 28.22 zettaFLOPs.', 'answer_value': 28.22, 'answer_unit': 'zettaFLOPs', 'ref_id': ['li2025a'], 'ref_url': 'is_blank', 'supporting_materials': 'is_blank', 'explanation': "Document [li2025a_p5] explicitly breaks down the total training cost of FLM-101B, stating that it was '28.22 zettaFLOPs for English'. Document [li2025a_p7] corroborates this value in Table 7, which lists the cost for FLM-101B as 28.22 zettaFLOPs in the context of the English SuperGLUE-IQ benchmark."}
{'id': 'q025', 'question': 'Which hardware processor was reported for the experimental setup of energy-efficient local inference in financial sentiment classification?', 'answer': 'The hardware processor used for the experimental setup of energy-efficient local inference in financial sentiment classification was an 11th Gen Intel(R) Core(TM) i7-1165G7 processor.', 'answer_value': '11th Gen Intel(R) Core(TM) i7-1165G7', 'answer_unit': 'is_blank', 'ref_id': ['khan2025'], 'ref_url': 'is_blank', 'supporting_materials': 'is_blank', 'explanation': "Document [khan2025_p4] describes an experiment using a 'Financial Sentiment Analysis' dataset and specifies the hardware setup under the 'Hardware and Software Setting' section, explicitly mentioning the '11th Gen Intel(R) Core(TM) i7-1165G7 processor'."}
{'id': 'q026', 'question': "How many different machine learning models were sampled and analyzed for the 'Power Hungry Processing' (2024) study on AI deployment costs?", 'answer': "The 'Power Hungry Processing' (2024) study sampled and analyzed 88 different machine learning models for their research on AI deployment costs.", 'answer_value': 88, 'answer_unit': 'models', 'ref_id': ['luccioni2024', 'zschache2025'], 'ref_url': 'is_blank', 'supporting_materials': 'is_blank', 'explanation': 'The ethical considerations statement in the original study mentions running experiments on "each of the 88 models". A separate document summarizing the study also confirms that it "systematically compared the energy costs of 88 models".'}
{'id': 'q027', 'question': 'By what factor does the overall carbon footprint decrease if GPU utilization is increased to 80% for Language Model (LM) training?', 'answer': 'When GPU utilization is increased to 80% for Language Model (LM) training, the overall carbon footprint decreases by a factor of 3.', 'answer_value': 3, 'answer_unit': 'multiplier', 'ref_id': ['wu2021a'], 'ref_url': 'is_blank', 'supporting_materials': 'is_blank', 'explanation': 'The document explicitly states that increasing GPU utilization up to 80% for LM training results in a 3x decrease in the overall carbon footprint, as this improves the efficiency of both operational and embodied carbon costs.'}
{'id': 'q028', 'question': 'Cottier et al. (2025) find that the total compute for model development is how many times larger than the compute for the final training run alone?', 'answer': 'The total compute for model development is estimated to be 1.2 to 4 times larger than the compute for the final training run alone.', 'answer_value': '[1.2,4]', 'answer_unit': 'multiplier', 'ref_id': ['cottier2024'], 'ref_url': 'is_blank', 'supporting_materials': 'is_blank', 'explanation': "To account for the compute cost over the entire model development process (including experiments, failed attempts, evaluation, and fine-tuning), a multiplicative factor is applied to the final training run's compute. This factor is sampled from a log-normal distribution with a 90% confidence interval of 1.2x to 4x."}
{'id': 'q029', 'question': 'What is the estimated total energy consumption (in MWh) for a full training run of a 6.1 billion parameter transformer model?', 'answer': 'The estimated total energy consumption for a full training run of a 6.1 billion parameter transformer model is 103.5 MWh.', 'answer_value': 103.5, 'answer_unit': 'MWh', 'ref_id': ['dodge2022'], 'ref_url': 'is_blank', 'supporting_materials': 'is_blank', 'explanation': 'Document [dodge2022_p7] states that training a 6.1 billion parameter model for 8 days, which represents only 13% of a full training run, consumed 13.8 MWh. The document then estimates that a full training run to completion would consume approximately 103.5 MWh.'}
{'id': 'q030', 'question': 'The central argument of one 2025 paper is that technical efficiency gains in AI may not lead to net environmental benefits due to what economic principle?', 'answer': "The central argument of the 2025 paper is that technical efficiency gains in AI may not lead to net environmental benefits due to the economic principle known as Jevons' Paradox, where efficiency gains can paradoxically spur increased consumption.", 'answer_value': "Jevons' Paradox", 'answer_unit': 'is_blank', 'ref_id': ['luccioni2025a'], 'ref_url': 'is_blank', 'supporting_materials': 'is_blank', 'explanation': "The paper, titled 'From Efficiency Gains to Rebound Effects: The Problem of Jevons’ Paradox in AI’s Polarized Environmental Debate', explicitly states in its abstract and introduction that it examines how Jevons' Paradox applies to AI, whereby efficiency gains may paradoxically lead to increased consumption, thus undermining net environmental benefits."}
{'id': 'q031', 'question': 'By 2027, the global AI demand is projected to account for how many billion cubic meters of water withdrawal?', 'answer': 'By 2027, the global AI demand is projected to account for a total water withdrawal of 4.2 to 6.6 billion cubic meters.', 'answer_value': '[4.2,6.6]', 'answer_unit': 'billion cubic meters', 'ref_id': ['jegham2025', 'li2025b'], 'ref_url': 'is_blank', 'supporting_materials': 'is_blank', 'explanation': 'The total projected water withdrawal is the sum of scope-1 (on-site cooling) and scope-2 (for electricity generation) water usage. Document [li2025b_p10] calculates the total by adding scope-1 withdrawal (0.11 – 0.16 billion cubic meters) and scope-2 withdrawal (4.10 – 6.46 billion cubic meters), resulting in a total of 4.2 – 6.6 billion cubic meters. This range is also stated in documents [li2025b_p1] and [li2025b_p2], and the upper limit is referenced in document [jegham2025_p2].'}
{'id': 'q032', 'question': 'True or False: As researchers have determined the well-known diminishing returns of increased cost of AI research, Red AI is on the decline.', 'answer': 'The statement is false. According to the provided documents, Red AI is on the rise, despite the well-known diminishing returns associated with increased computational costs.', 'answer_value': 0, 'answer_unit': 'is_blank', 'ref_id': ['schwartz2019'], 'ref_url': 'is_blank', 'supporting_materials': 'is_blank', 'explanation': 'Document [schwartz2019_p2] explicitly states, "Red AI is on the rise despite the well-known diminishing returns of increased cost (e.g., Figure 3)." This directly contradicts the premise that Red AI is on the decline.'}
{'id': 'q033', 'question': 'Using a growth strategy, what was the total wall-clock time required to train the FLM-101B model?', 'answer': 'The total wall-clock time required to train the FLM-101B model using a growth strategy was 21.54 days.', 'answer_value': 21.54, 'answer_unit': 'days', 'ref_id': ['li2025a'], 'ref_url': 'is_blank', 'supporting_materials': 'is_blank', 'explanation': 'The document explicitly states that the total time cost for training FLM-101B under the specified growth schedule is 21.54 days. This value is also the sum of the time taken for each growth stage as detailed in Table 1: 9.63 days for the 16B model, 5.37 days for the 51B model, and 6.54 days for the 101B model.'}
{'id': 'q034', 'question': 'True or False: At Facebook, a majority of model experimentation workflows utilize GPUs at over 80% capacity.', 'answer': 'False. A vast majority of model experimentation workflows at Facebook utilize GPUs at only 30-50% capacity.', 'answer_value': 0, 'answer_unit': 'is_blank', 'ref_id': ['wu2021a'], 'ref_url': 'is_blank', 'supporting_materials': 'is_blank', 'explanation': "Document [wu2021a_p8] explicitly states that a 'vast majority of model experimentation... utilizes GPUs at only 30-50%,' which directly contradicts the statement that utilization is over 80%."}
{'id': 'q035', 'question': 'How much electricity (in MWh) is the training of GPT-3 estimated to have consumed?', 'answer': 'The training of the GPT-3 model is estimated to have consumed 1,287 MWh of electricity.', 'answer_value': 1287, 'answer_unit': 'MWh', 'ref_id': ['jegham2025', 'patterson2021', 'li2025b'], 'ref_url': 'is_blank', 'supporting_materials': 'is_blank', 'explanation': 'Three separate documents confirm that the estimated energy consumption for training GPT-3 was 1287 MWh. Document [li2025b_p5] states, "GPT-3 was trained...with an estimated training energy of 1287 MWh". Document [jegham2025_p1] notes, "Training GPT-3 is estimated to consume 1,287 megawatt-hours (MWh) of electricity". Document [patterson2021_p7] also reports, "its energy consumption is 1287 MWh."'}
{'id': 'q036', 'question': 'What is the name of the collaborative project that aims to create a standardized method for comparing the inference efficiency of various AI models?', 'answer': 'The collaborative project aimed at establishing a standardized, unified approach for comparing the inference efficiency of AI models is called the AI Energy Score.', 'answer_value': 'AI Energy Score', 'answer_unit': 'is_blank', 'ref_id': ['luccioni2025c'], 'ref_url': 'is_blank', 'supporting_materials': 'is_blank', 'explanation': "Document [luccioni2025c_p2] explicitly mentions the 'AI Energy Score' as 'a project aiming to establish a unified approach for comparing the inference efficiency of AI models'."}
{'id': 'q037', 'question': 'For a dense BlackMamba model with a batch size of 30 fine-tuned with a NVIDIA A40-48 GB GPU, what was the execution time, in microseconds, for the longest kernel of the MoE layer?', 'answer': 'For a dense BlackMamba model fine-tuned with a batch size of 30 on an NVIDIA A40-48 GB GPU, the longest kernels of the MoE layer were `matmul(w1)` and `matmul(w2)`, each with an execution time of approximately 600 microseconds.', 'answer_value': 600, 'answer_unit': 'microseconds', 'ref_id': ['xia2024'], 'ref_url': 'is_blank', 'supporting_materials': 'is_blank', 'explanation': "Figure 6 in document [xia2024_p5] provides a kernel-level execution breakdown of the MoE layer. The bottom chart, labeled 'Mamba', shows data for the BlackMamba model. For the 'Dense(bsz=30)' configuration, the longest kernels are `matmul(w1)` and `matmul(w2)`, each taking approximately 600 microseconds (μs). Document [xia2024_p3] confirms the experiments were conducted on an NVIDIA A40 GPU."}
{'id': 'q038', 'question': 'In each layer of the JetMoE-8B model, how many experts are selected for activation (top-k) for a given token?', 'answer': 'In each layer of the JetMoE-8B model, 2 experts are selected for activation (top-k) for a given token.', 'answer_value': 2, 'answer_unit': 'experts', 'ref_id': ['shen2024'], 'ref_url': 'is_blank', 'supporting_materials': 'is_blank', 'explanation': "Document [shen2024_p6] provides a table of hyperparameters for the JetMoE-8B model, which explicitly lists 'Top-k' as 2. The accompanying text confirms this, stating, 'we set the same number of experts to 8 and top-k to 2 for every layer'."}
{'id': 'q039', 'question': 'True or False: deep learning models are increasingly large and computationally-intensive, with a 200,000x increase in the amount of compute used to train them over a six-year span (2012 -2018).', 'answer': 'False. While it is true that deep learning models are increasingly large and computationally-intensive, the provided documents state that the amount of compute used to train them increased by an estimated 300,000x over the six-year span from 2012 to 2018, not 200,000x.', 'answer_value': 0, 'answer_unit': 'is_blank', 'ref_id': ['schwartz2019'], 'ref_url': 'is_blank', 'supporting_materials': 'is_blank', 'explanation': 'The documents specify a 300,000x increase in the amount of compute used for training deep learning models between 2012 and 2018, which contradicts the 200,000x figure mentioned in the question.'}
{'id': 'q040', 'question': 'What was the reported drop in global carbon emissions in 2020 during the COVID-19 pandemic?', 'answer': 'During the COVID-19 pandemic, the global carbon emissions for 2020 dropped by 6.4 percent.', 'answer_value': 6.4, 'answer_unit': 'percent', 'ref_id': ['wu2021b'], 'ref_url': 'is_blank', 'supporting_materials': 'is_blank', 'explanation': "Document [wu2021b_p6] explicitly states that 'the global carbon emissions for 2020 dropped by 6.4%'."}
{'id': 'q041', 'question': 'In 2023, in how many of AWS data center regions was 100% of the electricity consumed matched with renewable energy sources?', 'answer': 'In 2023, 22 AWS data center regions had 100% of their electricity consumption matched with renewable energy sources.', 'answer_value': 22, 'answer_unit': 'data centers', 'ref_id': ['amazon2023'], 'ref_url': 'is_blank', 'supporting_materials': 'is_blank', 'explanation': 'The document states that in 2023, the electricity consumed by 22 AWS data center regions was fully matched with renewable energy sources, which is an increase from 19 regions in the previous year, 2022.'}
{'id': 'q042', 'question': 'What is the approximate age of the field of Artificial Intelligence in 2025?', 'answer': 'I am sorry, but the provided documents do not contain information about the founding date or the age of the field of Artificial Intelligence. Therefore, it is not possible to determine its approximate age in 2025 based on the given text.', 'answer_value': 'is_blank', 'answer_unit': 'years', 'ref_id': ['', 'l', 's', 'i', 'a', 'n', 'k', 'b'], 'ref_url': 'is_blank', 'supporting_materials': 'is_blank', 'explanation': 'The provided reference documents discuss various aspects of AI, including research papers, applications, and its environmental impact, but none of them mention the year the field was established, which is required to calculate its age.'}
{'id': 'q043', 'question': 'The well-known "five cars" carbon footprint estimate, originating from a 2019 study, is based on what specific and infrequently performed AI process?', 'answer': 'The "five cars" carbon footprint estimate from the 2019 Strubell et al. study is based on a large-scale and infrequently performed procedure called Neural Architecture Search (NAS).', 'answer_value': 'Neural Architecture Search', 'answer_unit': 'is_blank', 'ref_id': ['luccioni2023', 'luccioni2025c', 'dodge2022'], 'ref_url': 'is_blank', 'supporting_materials': 'is_blank', 'explanation': 'The reference documents state that the 2019 study by Strubell et al. estimated the emissions for a process called Neural Architecture Search (NAS). This specific workload is described as a large-scale procedure that is performed much less frequently than typical AI model training.'}
{'id': 'q044', 'question': 'For the Llama 3.1 8B model, by what percentage does energy use decrease when targeting an average Time Per Output Token (TPOT) of 100 ms instead of minimizing latency?', 'answer': 'For the Llama 3.1 8B model, targeting an average Time Per Output Token (TPOT) of 100 ms reduces energy consumption per generation by 44% compared to the configuration that minimizes latency.', 'answer_value': 44, 'answer_unit': 'percent', 'ref_id': ['chung2025'], 'ref_url': 'is_blank', 'supporting_materials': 'is_blank', 'explanation': 'Document [chung2025_p9] explicitly states that for a conversational AI service using Llama 3.1 8B, targeting an average TPOT of 100 ms can reduce energy consumption per generation by 44% compared to the configuration that simply minimizes latency.'}
{'id': 'q045', 'question': 'What is the maximum batch size (in samples) supported by fine-tuning BlackMamba with a sparse setup on the GSM8K dataset using a NVIDIA A40 GPU with 48 GB memory?', 'answer': 'The maximum batch size supported for fine-tuning the BlackMamba model with a sparse setup on the MATH dataset (which corresponds to the arithmetic reasoning task evaluated by GSM8K) is 8 samples on an NVIDIA A40 GPU with 48GB of memory.', 'answer_value': 8, 'answer_unit': 'samples', 'ref_id': ['xia2024'], 'ref_url': 'is_blank', 'supporting_materials': 'is_blank', 'explanation': "Table III in the document lists the maximum batch sizes for different models and datasets. For the 'BlackMamba-S' (sparse) model on the 'MATH' dataset, the supported batch size is 8. The text explicitly states that these experiments were conducted on an NVIDIA A40 GPU with 48GB memory."}
{'id': 'q046', 'question': 'As of 2023, how many gigawatts of energy storage capacity did Amazon hold?', 'answer': 'As of 2023, Amazon held 1.3 gigawatts of energy storage capacity.', 'answer_value': 1.3, 'answer_unit': 'GW', 'ref_id': ['amazon2023'], 'ref_url': 'is_blank', 'supporting_materials': 'is_blank', 'explanation': "Both documents state that Amazon's energy storage capacity was 1.3 GW in 2023. Document [amazon2023_p24] lists it as a key figure, and Document [amazon2023_p27] elaborates under the 'Energy Storage Solutions' section, mentioning 'We now hold 1.3 GW of storage capacity, up from 445 MW in 2022.'"}
{'id': 'q047', 'question': 'The annual carbon emissions from GPT-4o inference are projected to be comparable to the emissions from how many transatlantic flights?', 'answer': 'The projected annual carbon emissions from GPT-4o inference are comparable to the cumulative emissions from approximately 272 transatlantic flights between Boston and London.', 'answer_value': 272, 'answer_unit': 'flights', 'ref_id': ['jegham2025'], 'ref_url': 'is_blank', 'supporting_materials': 'is_blank', 'explanation': 'Document [jegham2025_p11] projects the annual carbon emissions of GPT-4o inference to be between 138,125 and 163,441 tons of CO2e, which is stated to be comparable to the emissions from approximately 272 transatlantic flights.'}
{'id': 'q048', 'question': 'What percentage of AI inference workloads in Asia were powered by coal in 2023?', 'answer': 'I am sorry, but the provided documents do not contain information about the percentage of AI inference workloads in Asia that were powered by coal in 2023.', 'answer_value': 'is_blank', 'answer_unit': 'percent', 'ref_id': ['', 'l', 's', 'i', 'a', 'n', 'k', 'b'], 'ref_url': 'is_blank', 'supporting_materials': 'is_blank', 'explanation': 'The reference documents discuss the energy consumption of AI and LLM inference, but they do not provide specific data on the energy sources, such as coal, used for these workloads in Asia during 2023.'}
{'id': 'q049', 'question': 'What was the global average power usage effectiveness (PUE) of AI-dedicated data centers in 2023?', 'answer': 'The global average power usage effectiveness (PUE) for data centers in 2023 was 1.58.', 'answer_value': 1.58, 'answer_unit': 'PUE', 'ref_id': ['ebert2024'], 'ref_url': 'is_blank', 'supporting_materials': 'is_blank', 'explanation': 'Document [ebert2024_p2] states that the average data center PUE in 2023 was 1.58 globally. The provided documents do not specify a separate PUE value exclusively for AI-dedicated data centers.'}

In [19]:
results_df.head(50)

,id,question,answer,answer_value,answer_unit,ref_id,ref_url,supporting_materials,explanation
0,q001,What was the average increase in U.S. data cen...,The total energy consumption of U.S. data cent...,4,percent,['wu2021b'],is_blank,is_blank,Document [wu2021b_p5] explicitly states that '...
1,q002,"In 2023, what was the estimated amount of cars...",The Amazon Solar Farm Maryland-CPV Backbone is...,13900,cars,['amazon2023'],is_blank,is_blank,Document [amazon2023_p27] explicitly states th...
2,q004,How many data centers did AWS begin using recy...,"In 2023, AWS increased the number of data cent...",4,data centers,['amazon2023'],is_blank,is_blank,"The document states that in 2023, AWS increase..."
3,q005,Since NVIDIA doesn't release the embodied carb...,Since NVIDIA does not disclose the embodied ca...,463,kg/GPU,['morrison2025'],is_blank,is_blank,The document explicitly states that due to the...
4,q006,By what factor was the estimated amortized tra...,The provided documents do not contain the nece...,is_blank,ratio,"['cottier2024', 'li2025a']",is_blank,is_blank,The estimated amortized training cost for GPT-...
5,q007,What is the approximate CO2e for a single pass...,The approximate carbon footprint (CO2e) for a ...,1.2,tCO2e,['patterson2021'],is_blank,is_blank,Document [patterson2021_p3] states in both the...
6,q008,"When evaluated on the Open LLM Leaderboard, wh...","When evaluated on the Open LLM Leaderboard, th...",43.94,score,['li2025a'],is_blank,is_blank,"Document [li2025a_p5] contains Table 4, which ..."
7,q010,By how many fold did processor clock speed imp...,"Between 1971 and 2021, the processor clock spe...",6750,fold,['wu2021b'],is_blank,is_blank,Document [wu2021b_p2] explicitly states that t...
8,q011,How many days did it take to train GPT-3 using...,It took approximately 14.8 days to train GPT-3...,14.8,days,['patterson2021'],is_blank,is_blank,Document [patterson2021_p18] explicitly states...
9,q012,What is the estimated GPU Power Usage in kWh f...,The estimated GPU Power Usage from SGLang benc...,0.036,kWh,['morrison2025'],is_blank,is_blank,Both documents provide a table detailing resou...
10,q013,What were the total permitted annual emission ...,"Between January 1, 2023, and December 1, 2024,...",13000,tons,['han2024'],is_blank,is_blank,The reference documents state that the total p...
11,q014,A 2025 paper compares its training time to a f...,Using the growth strategy for the FLM-101B mod...,72,percent,['li2025a'],is_blank,is_blank,Document [li2025a_p3] states that the total ti...
12,q015,Approximately how many premature deaths in 203...,The provided documents do not contain informat...,is_blank,deaths,['han2024'],is_blank,is_blank,The reference documents provide projections fo...
13,q016,Dodge et al. (2022) estimate that a full train...,Dodge et al. (2022) estimate that a full train...,60,days,['dodge2022'],is_blank,is_blank,The document states that the model was trained...
14,q017,"For the inference process, which model has the...",Based on the appendix data from the 2025 study...,Llama 2 13B,is_blank,['morrison2025'],is_blank,is_blank,"Table 4 in document [morrison2025_p16], which ..."
15,q018,In what year was the One Hundred Year Study on...,The One Hundred Year Study on Artificial Intel...,2014,year,['stone2022'],is_blank,is_blank,Document [stone2022_p1] explicitly states in t...
16,q019,According to the UN's Global E-Waste Monitor 2...,According to the UN's Global E-Waste Monitor 2...,22,percent,['luccioni2025a'],is_blank,is_blank,Document [luccioni2025a_p3] directly states th...
17,q020,What is the energy consumption (in MWh) for pr...,The energy consumption for pre-training the BL...,520,MWh,['luccioni2025c'],is_blank,is_blank,Document [luccioni2025c_p11] contains a table ...
18,q021,What percentage of the Switch Transformer's 15...,"The Switch Transformer, a large sparse model w...",0.1,percent,['patterson2021'],is_blank,is_blank,Document [patterson2021_p6] contains a bullet ...
19,q022,The JetMoE-8B architecture is a Mixture-of-Exp...,The JetMoE-8B architecture includes 8 experts ...,8,experts,['shen2024'],is_blank,is_blank,Document [shen2024_p6] provides a hyperparamet...
20,q023,"What is the total execution time, in seconds, ...",is_blank,is_blank,second,['is_blank'],is_blank,is_blank,is_blank
21,q024,"According to a cost estimation, how many zetta...","According to the provided documents, the estim...",28.22,zettaFLOPs,[li2025a],is_blank,is_blank,Document [li2025a_p5] explicitly breaks down t...
22,q025,Which hardware processor was reported for the ...,The hardware processor used for the experiment...,11th Gen Intel(R) Core(TM) i7-1165G7,is_blank,[khan2025],is_blank,is_blank,Document [khan2025_p4] describes an experiment...
23,q026,How many different machine learning models wer...,The 'Power Hungry Processing' (2024) study sam...,88,models,"[luccioni2024, zschache2025]",is_blank,is_blank,The ethical considerations statement in the or...
24,q027,By what factor does the overall carbon footpri...,When GPU utilization is increased to 80% for L...,3,multiplier,[wu2021a],is_blank,is_blank,The document explicitly states that increasing...
25,q028,Cottier et al. (2025) find that the total comp...,The total compute for model development is est...,"[1.2,4]",multiplier,[cottier2024],is_blank,is_blank,To account for the compute cost over the entir...
26,q029,What is the estimated total energy consumption...,The estimated total energy consumption for a f...,103.5,MWh,[dodge2022],is_blank,is_blank,Document [dodge2022_p7] states that training a...
27,q030,The central argument of one 2025 paper is that...,The central argument of the 2025 paper is that...,Jevons' Paradox,is_blank,[luccioni2025a],is_blank,is_blank,"The paper, titled 'From Efficiency Gains to Re..."
28,q031,"By 2027, the global AI demand is projected to ...","By 2027, the global AI demand is projected to ...","[4.2,6.6]",billion cubic meters,"[jegham2025, li2025b]",is_blank,is_blank,The total projected water withdrawal is the su...
29,q032,True or False: As researchers have determined ...,The statement is false. According to the provi...,0,is_blank,[schwartz2019],is_blank,is_blank,"Document [schwartz2019_p2] explicitly states, ..."
30,q033,"Using a growth strategy, what was the total wa...",The total wall-clock time required to train th...,21.54,days,[li2025a],is_blank,is_blank,The document explicitly states that the total ...
31,q034,"True or False: At Facebook, a majority of mode...",False. A vast majority of model experimentatio...,0,is_blank,[wu2021a],is_blank,is_blank,Document [wu2021a_p8] explicitly states that a...
32,q035,How much electricity (in MWh) is the training ...,The training of the GPT-3 model is estimated t...,1287,MWh,"[jegham2025, patterson2021, li2025b]",is_blank,is_blank,Three separate documents confirm that the esti...
33,q036,What is the name of the collaborative project ...,The collaborative project aimed at establishin...,AI Energy Score,is_blank,[luccioni2025c],is_blank,is_blank,Document [luccioni2025c_p2] explicitly mention...
34,q037,For a dense BlackMamba model with a batch size...,For a dense BlackMamba model fine-tuned with a...,600,microseconds,[xia2024],is_blank,is_blank,Figure 6 in document [xia2024_p5] provides a k...
35,q038,"In each layer of the JetMoE-8B model, how many...","In each layer of the JetMoE-8B model, 2 expert...",2,experts,[shen2024],is_blank,is_blank,Document [shen2024_p6] provides a table of hyp...
36,q039,True or False: deep learning models are increa...,False. While it is true that deep learning mod...,0,is_blank,[schwartz2019],is_blank,is_blank,"The documents specify a 300,000x increase in t..."
37,q040,What was the reported drop in global carbon em...,"During the COVID-19 pandemic, the global carbo...",6.4,percent,[wu2021b],is_blank,is_blank,Document [wu2021b_p6] explicitly states that '...
38,q041,"In 2023, in how many of AWS data center region...","In 2023, 22 AWS data center regions had 100% o...",22,data centers,[amazon2023],is_blank,is_blank,"The document states that in 2023, the electric..."
39,q042,What is the approximate age of the field of Ar...,"I am sorry, but the provided documents do not ...",is_blank,years,"[, l, s, i, a, n, k, b]",is_blank,is_blank,The provided reference documents discuss vario...
40,q043,"The well-known ""five cars"" carbon footprint es...","The ""five cars"" carbon footprint estimate from...",Neural Architecture Search,is_blank,"[luccioni2023, luccioni2025c, dodge2022]",is_blank,is_blank,The reference documents state that the 2019 st...
41,q044,"For the Llama 3.1 8B model, by what percentage...","For the Llama 3.1 8B model, targeting an avera...",44,percent,[chung2025],is_blank,is_blank,Document [chung2025_p9] explicitly states that...
42,q045,What is the maximum batch size (in samples) su...,The maximum batch size supported for fine-tuni...,8,samples,[xia2024],is_blank,is_blank,Table III in the document lists the maximum ba...
43,q046,"As of 2023, how many gigawatts of energy stora...","As of 2023, Amazon held 1.3 gigawatts of energ...",1.3,GW,[amazon2023],is_blank,is_blank,Both documents state that Amazon's energy stor...
44,q047,The annual carbon emissions from GPT-4o infere...,The projected annual carbon emissions from GPT...,272,flights,[jegham2025],is_blank,is_blank,Document [jegham2025_p11] projects the annual ...
45,q048,What percentage of AI inference workloads in A...,"I am sorry, but the provided documents do not ...",is_blank,percent,"[, l, s, i, a, n, k, b]",is_blank,is_blank,The reference documents discuss the energy con...
46,q049,What was the global average power usage effect...,The global average power usage effectiveness (...,1.58,PUE,[ebert2024],is_blank,is_blank,Document [ebert2024_p2] states that the averag...
47,q050,"During inference, how many of JetMoE-8B's para...",JetMoE-8B activates 2 billion parameters for e...,2000000000,parameters,[shen2024],is_blank,is_blank,The documents state that JetMoE-8B has a total...
48,q051,What are the GHG emissions (in tCO2e) associat...,The Greenhouse Gas (GHG) emissions associated ...,14,tCO2e,[luccioni2025c],is_blank,is_blank,Document [luccioni2025c_p11] contains a table ...
49,q052,How many Amazon electric delivery vans were ad...,"By the end of 2023, Amazon had added a cumulat...",19000,electric delivery vans,[amazon2023],is_blank,is_blank,"Document [amazon2023_p17] states that in 2023,..."

In [ ]:
df = results_df.copy()
df.loc[df['answer_value'] == 'is_blank', 'answer_unit'] = 'is_blank'
df.loc[df['answer_value'] == 'is_blank', 'ref_id'] = 'is_blank'

df.head(10)

,id,question,answer,answer_value,answer_unit,ref_id,ref_url,supporting_materials,explanation
0,q001,What was the average increase in U.S. data cen...,The total energy consumption of U.S. data cent...,4,percent,[wu2021b],is_blank,is_blank,"Document wu2021b_p5 explicitly states, 'The to..."
1,q002,"In 2023, what was the estimated amount of cars...","In 2023, the Amazon Solar Farm Maryland-CPV Ba...",13900,cars,[amazon2023],is_blank,is_blank,"Document amazon2023_p27, under the section ""Br..."
2,q004,How many data centers did AWS begin using recy...,"In 2023, AWS added four data centers that use ...",4,data centers,[amazon2023],is_blank,is_blank,According to the 'Using More Sustainable Sourc...
3,q005,Since NVIDIA doesn't release the embodied carb...,Since NVIDIA does not release data on the embo...,463,kg/GPU,[morrison2025],is_blank,is_blank,"Document morrison2025_p6, under the ""Hardware ..."
4,q006,By what factor was the estimated amortized tra...,The provided documents do not contain sufficie...,is_blank,is_blank,is_blank,is_blank,is_blank,Document cottier2024_p9 provides the estimated...
5,q007,What is the approximate CO2e for a single pass...,The approximate CO2e for a single passenger ro...,1.2,tCO2e,[patterson2021],is_blank,is_blank,Document patterson2021_p3 states in the text a...
6,q008,"When evaluated on the Open LLM Leaderboard, wh...","When evaluated on the Open LLM Leaderboard, th...",43.94,score,[li2025a],is_blank,is_blank,"Document li2025a_p5 provides Table 4, which de..."
7,q010,By how many fold did processor clock speed imp...,"Between 1971 and 2021, the processor clock spe...",6750,fold,[wu2021b],is_blank,is_blank,Document wu2021b_p2 states that the first comm...
8,q011,How many days did it take to train GPT-3 using...,"Training GPT-3 on 10,000 V100 GPUs, with each ...",14.8,days,[patterson2021],is_blank,is_blank,Document patterson2021_p18 explicitly states u...
9,q012,What is the estimated GPU Power Usage in kWh f...,The estimated GPU Power Usage from SGLang benc...,0.036,kWh,[morrison2025],is_blank,is_blank,The answer is found in Table 4 of Document mor...

In [16]:
df.to_csv('../data/no_unit_submission.csv', index=False)